PlayListFilePath: ""
SnapShotFolderPath: ""
Frames: 3
Duration: 00:00:10
Interval: 00:00:05
Randomize:
  MinStartMsec: 1000
  MaxEndMsec: 3000
PlayerLib:
  FFmpegPath: "ffmpeg"
  PlayFailedMsg: "{0}の再生に失敗しました。"
SubPlayer:
  Width: 300
  Height: 172
  Rate: 0.5
  RepeatDuration: 3000
MainPlayer:
  Height: 720
  Width: 1280
RootComponent:
  Margin: 8